### ISSUE TITLE
Action promises issue

### ISSUE THREAD

**Issue by maderesponsively** [bencompton/framework7-redux#12]
Hello,

I'm trying to get the 'getActionPromise' examples working. The redux dispatches and modals are working but no promises are being returned.  Has anyone else managed to get this working?

**Comment by bencompton** [comment]
I am using `getActionPromise` in one of my projects and it is working fine for my uses. I also just did a quick test in the [starter template](https://github.com/bencompton/framework7-redux-app-template) LoginActions.js:

```javascript
export const login = () => {
    return (dispatch, getState) => {
      if (loginValid(getState())) {
        dispatch(closeLogin());
      } else {
        stateKernel.getActionPromise(closeAlert().type).then(() => console.log('closed'));

        dispatch(showAlert('Incorrect password! Hint: please enter "password!".', 'Failed Login'));
      }
    };
};
```

When I go to the login page, enter incorrect credentials, and then close the alert, "closed" gets logged to the console just as I would expect.

**Comment by maderesponsively** [comment]
Thanks, @bencompton, I'll do some more investigation on my side.
