### ISSUE TITLE
Working Example

### ISSUE THREAD

**Issue by vauvenal5** [bencompton/framework7-redux#3]
Hi,

is there somewhere a working example? I was not able to get navigation working with Framework7-Ract together with this framework. To be more precise when I set it up like described in the README with dynamic routes I can navigate once and afterwards it does not navigate anymore.

Cheers!

**Comment by bencompton** [comment]
There are currently no working examples available--it is on the todo list to provide a comprehensive set of examples. In the meantime, if you would care to share some code demonstrating your issue, I would be more than happy to help.

**Comment by bencompton** [comment]
A [working example](https://github.com/bencompton/framework7-redux-app-template) has finally been created for use with Framework7 v3 and React.
