### ISSUE TITLE
How does navigation work with <Link/>, etc?

### ISSUE THREAD

**Issue by JasonKleban** [bencompton/framework7-redux#4]
I'm converting an old abandoned, but partially working project from non-react Framework7 to Framework7+React+Redux.  I'm barely familiar with React/Redux at this point, but I like JSX.  I'm having trouble separating out the best practices of the various scenarios to make this work.  I'm aiming for a DOM Cache inline-style with dynamic navbars.

I have my app to the point where my default Page loads correctly in the main view.  But I can't get the navigation links to work.  I have `<Framework7App onFramework7Init={() => store.dispatch(navigateTo('/'))} routes={Routes} themeType="ios" router={false} stateKernel={framework7StateKernel}>` and that all seems to be necessary. 

But I can't get links to work.  These seem discouraged in framework7-redux:

```
<Link href="/about/">About App</Link>
<Link href="/login/">Login</Link>
```
or
```
<Link onClick={() => getFramework7().mainView.router.loadPage('/about/')}>About</Link>
<Link onClick={() => getFramework7().mainView.router.back()}>Go Back</Link>
```

but I don't know how to really make use of this instead:
```
//Go to page 1
store.dispatch(navigateTo('/page-1/'));

//Go back to the home page
store.dispatch(goBack());
```
Can you please elaborate on it?

Thanks!

**Comment by bencompton** [comment]
This project is still pretty new, and I still need to put together some examples. In the meantime, see if this helps:

```javascript
//HomePage.jsx

const HomePage = ({onAboutSelected, onBackSelected}) => (
	...
	<Link onClick={onBackSelected}>Go Back</Link>
	<Link onClick={onAboutSelected}>About App</Link>
	...	
);

//HomeActions.js

import {navigateTo, goBack} from 'framework7-redux';

export const backSelected = () => {
	return goBack();
};

export const aboutSelected = () => {
	return navigateTo('/about/');
};

//HomePageContainer.jsx

import {connect} from 'react-redux';
import {goBackSelected, aboutSelected} from './actions/HomeActions';

import {HomePage} from './components/HomePage';

const mapDispatchToProps = dispatch => {
	return {
		onBackSelected: dispatch(backSelected()),
		onAboutSelected: dispatch(aboutSelected())
	};
};

export const HomePageContainer = connect(
  null,
  mapDispatchToProps
)(HomePage);

//routes.js

import {HomePageContainer} from './containers/HomePageContainer';
import {AboutPageContainer} from './containers/AboutPageContainer';

export const routes = [{
	path: '/',
	component: HomePageContainer
}, {
	path: '/about/',
	component: AboutPageContainer
}];
```

**Comment by JasonKleban** [comment]
Alright!  Thanks!  Almost there I think.  

Any idea about this runtime error?  What did I miss?

```
Uncaught TypeError: Cannot read property 'route' of undefined
    at HistoryReconciler.get [as currentF7HistoryPagePath] (http://localhost:8888/app.js:42265:103)
    at HistoryReconciler.fastForwardToFirstNonMatchingPage (http://localhost:8888/app.js:42278:77)
    at HistoryReconciler.getOperationsToReconcileHistories (http://localhost:8888/app.js:42239:14)
    at RoutingKernel.reconcileHistories (http://localhost:8888/app.js:42190:14)
    at RoutingKernel.handleStateChange (http://localhost:8888/app.js:42171:14)
    at RoutingKernel.StateKernel.setState (http://localhost:8888/app.js:7704:18)
    at http://localhost:8888/app.js:7708:19
    at Array.forEach (native)
    at Framework7StateKernel.StateKernel.setState (http://localhost:8888/app.js:7707:23)
    at Array.<anonymous> (http://localhost:8888/app.js:41951:21)
```

**Comment by bencompton** [comment]
It looks like you might not have passed your framework7StateKernel into your Framework7App component, which would result in some things not getting initialized properly. Hopefully this will help:

```javascript
import {Provider} from 'react-redux';
import {store, framework7StateKernel} from './store';

<Provider store={store}>
  <Framework7App
    themeType={'ios'}
    routes={routes}
    router={false}
    stateKernel={framework7StateKernel}
  >
  ...
  </Framework7App>
</Provider>
```

**Comment by JasonKleban** [comment]
I think I have it exactly like that.  I'm using the dom cache mode where everything is already loaded and available without any followup downloads necessary from the server - does that make a difference?  I tried adding `<Framework7App ... cache>` but that had no immediate effect.

**Comment by bencompton** [comment]
Using the DOM cache like the kitchen sink does is the default way of working, so there shouldn't be any problems there. Are you still having issues getting it to work or did you figure it out? Guess I really need to put a working example / template out soon there so people won't have to spend as much time trying to get it working.

**Comment by JasonKleban** [comment]
I did not figure it out yet.  Seems like `findMatchingRoute()` in `history-reconciler.js` cannot resolve `findMatchingRoute("#Today")` from this routes object:

```
[{
  path: '#Today',
  component: Today
},{
  path: '#MyAccount',
  component: MyAccount
}];
```

Where my `<Page name="Today" />` is the starting page.  #Today is being sought automatically based on the active page name, I think, before getting to the part where it navigates to the NEW page that I requested using `dispatch(navigateTo("#MyAccount"))`.

I tried debugging `findMatchingRoute()` but I'm not sure _exactly_ what it's supposed to do, so I can't tell if there's a bug there, or something wrong with my usage.

**Comment by JasonKleban** [comment]
I'm still unable to get routing to work at all.

![image](https://user-images.githubusercontent.com/17498172/27587049-d24fd798-5b10-11e7-9b18-215af9e794f9.png)

~~I believe it is getting `#Today` from `<Page name="Today" />` being the non-`cached` view.~~  So when I click on any link, for example `dispatch(navigateTo("#MyAccount"))`, the currentF7HistoryPagePath fails to `findMatchingRoute("#Today")` and I get the type error.

![image](https://user-images.githubusercontent.com/17498172/27586725-8503770c-5b0f-11e7-8dfd-519dc14c6ca1.png)

Even if I try to replace "#Today" with "/Today" in all places, the current history is still "#Today".  I've also tried making links go to "/MyAccount" and just "MyAccount" but it makes no difference.

Any thoughts?

Thanks

**Comment by JasonKleban** [comment]
Ok, I think this is mostly because `#Today` was my main Page and among my routes, but the url is `/` when it loads (which matches none of my explicit routes) and not `#Today`, `/Today/`, nor `Today` so it can't find the previous route.  If I change my routes and links to be `/` then I get further - the page name can stay as `Today`.  Is there more you can explain about the custom routing mechanism here?

![image](https://user-images.githubusercontent.com/17498172/27619668-252a3b3a-5b92-11e7-9d0f-897b27e37e41.png)

I don't know if this is all part of the same mistake I've made or if it should be a different issue, but the next thing I run into is that `self.$parent` is `undefined` in onRouteChange on one of the iterations.  I'm trying to track through the code to find out what `self` is and why it has no `$parent`, but I'm having a very difficult time of that.
