### ISSUE TITLE
Exporting framework7-actions

### ISSUE THREAD

**Issue by JasonKleban** [bencompton/framework7-redux#5]
I'm using typescript, and *I think* this resulting index.ts should be this instead:

```
export { Framework7StateKernel } from './state-kernels/framework7-kernel';
export { showAlert, closeAlert, showPreloader, hidePreloader } from './redux/actions/modal-actions';
export { navigateTo, goBack } from './redux/actions/routing-actions';
export { framework7Reducer } from './redux/reducers/framework7-reducer';
export { IFramework7State } from './state/framework7-state';
export { syncFramework7WithStore } from './redux/sync';
export { ShowAlertAction, CloseAlertAction, ShowPreloaderAction, 
    HidePreloaderAction, ModalAction, RoutingAction, NavigateToAction, 
    GoBackAction } from './redux/actions/framework7-actions';
```

especially the last line, because then I can type these properly:

```
interface ComponentStateProps {
}

interface ComponentDispatchProps {
    onGo: (page: string) => () => RoutingAction
}

type PanelLeftProps = ComponentStateProps & ComponentDispatchProps;

export const PanelLeft =
    connect<ComponentStateProps, ComponentDispatchProps, {}>(
        (state, ownProp?) => ({

        }),
        (dispatch) => ({
            onGo: (page: string) => () => dispatch(navigateTo(page))
        }))(
        class extends React.Component<PanelLeftProps, {}> {
            constructor(public props: PanelLeftProps) {
                super();
            }

            render() {
                return <Panel left reveal> ...
                                <ListItem
                                    onClick={this.props.onGo('#Home')} ...
```

This is the least redundant, most anonymous, most inferred version I could come up with so far.

**Comment by bencompton** [comment]
Those action types are the return types of the action creator functions. Normally TypeScript errors if something is exported but a type it depends on is not exported. For some reason, TypeScript didn't throw an error in this case. I can definitely see where those types would be useful and should be exported. Also, I normally separate imports and exports, but I actually like your proposed, more concise syntax better.

Feel free to make a PR if you like, or otherwise, I'll go ahead and add your proposed changes when I get a chance.

**Comment by JasonKleban** [comment]
I believe it doesn't error here because type aliases behave different than interfaces.  See ["Interfaces vs. Type Aliases"](https://www.typescriptlang.org/docs/handbook/advanced-types.html) in the docs.

Especially: "A second more important difference is that type aliases cannot be extended or implemented from (nor can they extend/implement other types). Because an ideal property of software is being open to extension, you should always use an interface over a type alias if possible."

In my PR I'll change that too.
