### ISSUE TITLE
Framework7-react and server side rendering with framework7-redux question

### ISSUE THREAD

**Issue by khelkun** [bencompton/framework7-redux#7]
I've started to work from a MERN stack boilerplate. I was expecting to be able to use framework7-react in it but I'm stuck on server side rendering.
To be honest  I'm still not fully understanding Redux React-router and how's the server side rendering is done.
Quoting your Readme:
> If you want to control things like navigation and alert dialogs from Redux actions and want these things to work when you do server rendering 

So does Framework7-redux can allow to render Framework7-react component server side?
So far I have followed your Readme to be able to use Framework7App but if I want to use any framework7-react component in my own React component then I try something like this:
```
import React from 'react';
import PropTypes from 'prop-types';

import { LoginScreen } from 'framework7-react';

function UvLoginScreen(props, context) {
  return (
    <LoginScreen />
  );
}

UvLoginScreen.propTypes = {
};

export default UvLoginScreen;
```
But this `import LoginScreen` fails this way:
```
.../node_modules/framework7-react/dist/commonjs/framework7/Framework7.js:15
window.Dom7 = module.exports.Dom7 = (function () {
^
ReferenceError: window is not defined
```
I understand window object doesn't exists server side in the NodeJS context, but does framework-redux can help here?

**Comment by bencompton** [comment]
Server rendering is not a well-blazed path at the moment with Framework7 React and Framework7 Vue. The issues are with the Framework7 Router, so Framework7 Redux won't be of much help. Server rendering hasn't risen as a top priority, so there aren't any examples available yet, and there are likely a number of bugs that have not been flushed out yet.

**Comment by khelkun** [comment]
Thanks for your answer
