### ISSUE TITLE
Issue on using preLoader

### ISSUE THREAD

**Issue by RaphFuentes** [bencompton/framework7-redux#8]
Good day!

Are the preloaders and alerts already working?

I am using the framework7-react template together with this however I am getting the ff. error

Uncaught TypeError: Cannot read property 'showPreloader' of undefined
    at PreloaderKernel.showPreloader (preloader-kernel.js:32)
    at PreloaderKernel.handleStateChange (preloader-kernel.js:24)
    at PreloaderKernel.StateKernel.setState (state-kernel.js:15)
    at state-kernel.js:19
    at Array.forEach (<anonymous>)
    at ModalKernel.StateKernel.setState (state-kernel.js:18)
    at state-kernel.js:19
    at Array.forEach (<anonymous>)
    at Framework7StateKernel.StateKernel.setState (state-kernel.js:18)
    at Array.<anonymous> (sync.js:5)

I have also done as what is stated in the tutorial
```
export const framework7StateKernel = new Framework7StateKernel();

export const store = createStore(
	combineReducers({
		framework7: framework7Reducer
	})
);

syncFramework7WithStore(store, framework7StateKernel);
```

```
	<Provider store={store}>
		<Framework7App themeType="ios" routes={routes} router={false}
			stateKernel={framework7StateKernel}>
			<Statusbar />
			<LeftPanel />
			<RightPanel />
			<MainViews />
			<AppPopup />
			<AppLoginScreen />
		</Framework7App>
	</Provider>
```

Is there anything wrong on my setup? Thank you

**Comment by bencompton** [comment]
I don't see anything wrong in your sample code. I threw together a quick and dirty [example](https://github.com/bencompton/framework7-redux-app-template), and it appears to work in my tests. Try cloning that repo and selecting the "Preloader" and "Alert" buttons.

I know it's a bit hard to get started with this library without a starter template. #3 has been around for quite a while, and I intend to have a working F7 Redux app template for Framework7 v3, along with the normal [F7 React app template](https://github.com/framework7io/framework7-react-app-template/tree/v3).
