### ISSUE TITLE
Behaviour of navigateTo

### ISSUE THREAD

**Issue by raphElzr** [bencompton/framework7-redux#9]
Good Day!

I was using navigateTo to route on pages and I am having this behaviour.

Went to home page "/"
Went to register "/register/"
Went back (used goBack() or the default backLink="Back") << was navigated to home page as expected
Went to login "/login/"
Went back << Was navigated to register instead of home page

Looking at the framework7 routing history I have the ff.
history["/", "/register/",  "/login/"]

I guess the issue here is that register should have been overwritten by login? or is this behaviour expected? 

Thanks!

**Comment by bencompton** [comment]
@Zaxel - that's certainly not the behavior I would expect. The `/register/` route should have been removed when you went back to the home page the first time, and then the `/login/` route should have been the second item in the history after you navigated to that route.

**Comment by bencompton** [comment]
I added a navigation test [here](https://github.com/bencompton/framework7-redux-app-template) and don't see the behavior you describe. Try cloning the linked repo and then try the following steps (after `npm install` and `npm start`):

1. In the left sliding panel under "LOAD PAGE IN MAIN VIEW", select "About"
2. Go back
3. In the left sliding panel under "LOAD PAGE IN MAIN VIEW", select "Form"
4. Go back

In my tests, it returns to the home page as expected in both cases.

**Comment by raphElzr** [comment]
Thank you! The template was very helpful.
It seems that my issue was caused by 2 things
1.  forgot to turned router off in Framework7App
2. Forgot to use onBackClick Navbar event as shown in the template

Thanks!
